apiVersion: v1
kind: Service
metadata:
  name: myapp-jenkins
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: myapp
