apiVersion: v1
kind: Service
metadata:
  name: myapp-jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080
      nodePort: 30000
      targetPort: 8080
